name: docker-build-ecr
description: build and push docker image to AWS ECR
inputs:
  aws_region:
    description: The AWS region of the ECR registry
    required: true
  aws_role_arn:
    description: The ARN of the role to authenticate with
    required: true
  ecr_registry:
    description: The name of the ECR registry
    required: true
  ecr_repository:
    description: The name of the ECR repository
    required: true
  ecr_cache_repository:
    description: The name of the ECR repository to use for build caching
    required: false
  tag:
    description: The image tag
    required: true
outputs:
  digest:
    description: The image digest
    value: ${{ steps.build_and_push.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      id: aws_auth
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role_arn }}

    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.ecr_registry }}

    - name: Build and Push Docker Image
      id: build_and_push
      uses: docker/build-push-action@v6
      with:
        context: .
        # Only building for AMD64 for now
        # platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }}
          ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ inputs.tag }}
        cache-from: ${{ inputs.ecr_cache_repository && format('type=registry,ref={0}/{1}:latest', inputs.ecr_registry, inputs.ecr_cache_repository) || '' }}
        cache-to: ${{ inputs.ecr_cache_repository && format('type=registry,ref={0}/{1}:latest,mode=max,oci-mediatypes=true,image-manifest=true', inputs.ecr_registry, inputs.ecr_cache_repository) || '' }}
