name: Docker Build

on:
  workflow_call:
    inputs:
      architecture:
        default: linux/amd64
        description: The target CPU architecture to build the image for
        required: false
        type: string
      build_args:
        description: Build arguments to pass to docker build
        required: false
        type: string
      enable_caching:
        default: true
        description: Whether to enable the docker build cache
        required: false
        type: boolean
      provenance:
        default: true
        description: Whether to generate provenance for the image
        required: false
        type: boolean
      push:
        default: true
        description: Whether to push the image to a remote repository
        required: false
        type: boolean
    outputs:
      digest:
        description: The image digest
        value: ${{ jobs.build_push.outputs.digest }}

env:
  branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

jobs:
  build_push:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build_and_push.outputs.digest }}
    steps:
      - name: Configure AWS Credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Login to ECR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ${{ vars.ECR_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: |
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}
          tags: |
            type=raw,value=${{ env.branch }}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD' tz='Australia/Sydney'}},enable={{is_default_branch}}

      - name: Build and Push Docker Image
        id: build_and_push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          build-args: ${{ inputs.build_args }}
          platforms: ${{ inputs.architecture }}
          provenance: ${{ inputs.provenance }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: ${{ inputs.enable_caching && format('type=registry,ref={0}/{1}:latest', vars.ECR_REGISTRY, vars.ECR_CACHE_REPOSITORY) }}
          cache-to: ${{ inputs.enable_caching && format('type=registry,ref={0}/{1}:latest,mode=max,oci-mediatypes=true,image-manifest=true', vars.ECR_REGISTRY, vars.ECR_CACHE_REPOSITORY) }}
