name: Sync Mirrors

on: push

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v2
        id: app_token
        with:
          app-id: ${{ vars.DEVOPS_ISW_APP_ID }}
          private-key: ${{ secrets.DEVOPS_ISW_APP_PRIVATE_KEY }}
          owner: ISW-Cloud42
          repositories: github-actions

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync mirrors
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ steps.app_token.outputs.token }}@github.com/ISW-Cloud42/github-actions.git
          cd github-actions
          git remote add source https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git fetch source
          git reset --hard source/main
          git push origin main --force
