name: Pre-Commit Checks

on:
  workflow_call:

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          # renovate: datasource=github-tags depName=python/cpython extractVersion=^v(?<version>.*)$
          python-version: 3.14.6

      - name: Cache Go Modules
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # renovate: datasource=github-tags depName=golang/go extractVersion=^go(?<version>.*)$
          go-version: 1.26.5

      - name: Setup Terraform Docs
        run: go install github.com/terraform-docs/terraform-docs@v0.24.0

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@81e514348e19b6112ce2a7e3ecbafe19c1e1f567 # v0.3.1
        with:
          # renovate: datasource=github-releases depName=aquasecurity/trivy
          version: v0.72.0

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          # renovate: datasource=github-releases depName=opentofu/opentofu extractVersion=^v(?<version>.*)$
          tofu_version: 1.12.5
          tofu_wrapper: false

      - name: Run Pre-Commit Checks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
